# Configure roles in a database at a schema level
# This will add the following roles.
# NB: Removing roles will not remove them on the database if they have already been applied.

database: cleanair_test_db

schema: 

  - dynamic_data 
  - dynamic_features 
  - gla_traffic
  - interest_points
  - model_features
  - air_quality_modelling
  - processed_data
  - static_data
  - static_features
  - traffic_modelling
  - jamcam

roles:
  - role: readonly
    create_schema: False
    schema: 
      - name: dynamic_data 
        create: False
        privileges: 
          - SELECT
      - name: dynamic_features 
        create: False
        privileges: 
          - SELECT
      - name: gla_traffic
        create: False
        privileges: 
          - SELECT
      - name: interest_points
        create: False
        privileges: 
          - SELECT
      - name: model_features
        create: False
        privileges: 
          - SELECT
      - name: air_quality_modelling
        create: False
        privileges: 
          - SELECT
      - name: processed_data
        create: False
        privileges: 
          - SELECT
      - name: static_data
        create: False
        privileges: 
          - SELECT
      - name: static_features
        create: False
        privileges: 
          - SELECT
      - name: traffic_modelling
        create: False
        privileges: 
          - SELECT
      - name: jamcam
        create: False
        privileges:
          - SELECT

  - role: readwrite
    create_schema: False
    schema: 
      - name: dynamic_data 
        create: False
        privileges: 
          - ALL
      - name: dynamic_features 
        create: False
        privileges: 
          - ALL
      - name: gla_traffic
        create: False
        privileges: 
          - ALL
      - name: interest_points
        create: False
        privileges: 
          - ALL
      - name: model_features
        create: False
        privileges: 
          - ALL
      - name: air_quality_modelling
        create: False
        privileges: 
          - ALL
      - name: processed_data
        create: False
        privileges: 
          - ALL
      - name: static_data
        create: False
        privileges: 
          - ALL
      - name: static_features
        create: False
        privileges: 
          - ALL
      - name: traffic_modelling
        create: False
        privileges: 
          - ALL
      - name: jamcam
        create: False
        privileges:
          - ALL

  - role: readwritecreate
    create_schema: False
    schema: 
      - name: dynamic_data 
        create: True
        privileges: 
          - ALL
      - name: dynamic_features 
        create: True
        privileges: 
          - ALL
      - name: gla_traffic
        create: True
        privileges: 
          - ALL
      - name: interest_points
        create: True
        privileges: 
          - ALL
      - name: model_features
        create: True
        privileges: 
          - ALL
      - name: air_quality_modelling
        create: True
        privileges: 
          - ALL
      - name: processed_data
        create: True
        privileges: 
          - ALL
      - name: static_data
        create: True
        privileges: 
          - ALL
      - name: static_features
        create: True
        privileges: 
          - ALL
      - name: traffic_modelling
        create: True
        privileges: 
          - ALL
      - name: jamcam
        create: True
        privileges:
          - ALL

  - role: jamcamreadwrite
    create_schema: False
    schema:
      - name: jamcam
        create: True
        privileges:
          - ALL

  - role: jamcamread
    create_schema: False
    schema:
      - name: jamcam
        create: False
        privileges:
          - SELECT

  - role: trafficmodelling
    create_schema: False
    schema:
      - name: traffic_modelling
        create: False
        privileges:
          - ALL