apiVersion: v2
name: cleanair
description: A Helm chart for the CleanAir Kubernetes cluster

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.0.0

home: https://github.com/alan-turing-institute/clean-air-infrastructure

sources:
  - https://github.com/alan-turing-institute/clean-air-infrastructure

maintainers:
  - name: James Robinson
    email: jrobinson@turing.ac.uk
  - name: Oscar Giles
    email: ogiles@turing.ac.uk

dependencies:
  # https://github.com/helm/charts/tree/master/stable/nginx-ingress
  # 2021-01-05 OG: Migrated to https://github.com/kubernetes/ingress-nginx/ 
  - name: "ingress-nginx"
    version: "v3.34.0"
    repository: "https://kubernetes.github.io/ingress-nginx"
  - name: cert-manager
    version: "v0.13.0"
    repository: "https://charts.jetstack.io"
