imageTag: 0e90fe18179d85ef2b137112f40544e3bb827509

jobs:  
  - name: ukmap
    image:
      repository: cleanairdocker.azurecr.io/ukmap
      imagePullPolicy: Always
    schedule: "0,30 0 * * *"
    failedJobsHistoryLimit: 10
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: secrets

  - name: streetcanyon
    image:
      repository: cleanairdocker.azurecr.io/streetcanyon
      imagePullPolicy: Always
    schedule: "0,30 0 * * *"
    failedJobsHistoryLimit: 10
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: secrets

  - name: oshighway
    image:
      repository: cleanairdocker.azurecr.io/oshighway
      imagePullPolicy: Always
    schedule: "0,30 0 * * *"
    failedJobsHistoryLimit: 10
    successfulJobsHistoryLimit: 1
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: secrets

  - name: laqn
    image:
      repository: cleanairdocker.azurecr.io/laqn
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: secrets

  - name: aqe
    image:
      repository: cleanairdocker.azurecr.io/aqe
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: secrets

  - name: scoot
    image:
      repository: cleanairdocker.azurecr.io/scoot
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: secrets


# deployments:

#     - name: cleanairapi
#       replicas: 2
#       image: 
#         repository: cleanairdocker.azurecr.io/cleanairapi
#         imagePullPolicy: Always
#       ports:
#         containerPort: 80
