jobs:
  # first cron
  - name: laqn
    image:
      repository: cleanaircontainerregistry.azurecr.io/laqn
      tag: latest
      imagePullPolicy: Always
    schedule: "* * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: laqncred
      secret:
        secretName: laqncred

  - name: aqe
    image:
      repository: cleanaircontainerregistry.azurecr.io/aqe
      tag: latest
      imagePullPolicy: Always
    schedule: "* * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: aqecred
      secret:
        secretName: aqecred