jobs:
  # first cron
  - name: laqn
    image:
      repository: cleanairdocker.azurecr.io/laqn
      tag: ffc33a33452d02e1969e8ff0f19803c6f2e60573
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: secrets

  - name: aqe
    image:
      repository: cleanairdocker.azurecr.io/aqe
      tag: ffc33a33452d02e1969e8ff0f19803c6f2e60573
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: secrets

  - name: scoot
    image:
      repository: cleanairdocker.azurecr.io/scoot
      tag: ffc33a33452d02e1969e8ff0f19803c6f2e60573
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: secrets
