jobs:
  # first cron
  - name: laqn
    image:
      repository: cleanairdocker.azurecr.io/laqn
      tag: 86fe673b542e8dec877d64a842e21516339d1ad9
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: db-secrets

  - name: aqe
    image:
      repository: cleanairdocker.azurecr.io/aqe
      tag: 86fe673b542e8dec877d64a842e21516339d1ad9
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: db-secrets

  - name: scoot
    image:
      repository: cleanairdocker.azurecr.io/scoot
      tag: 86fe673b542e8dec877d64a842e21516339d1ad9
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets2
      secret:
        secretName: db-secrets
