jobs:
  # first cron
  - name: laqn
    image:
      repository: cleanairtesting.azurecr.io/laqn
      tag: latest
      pullPolicy: Always
      imagePullSecret: regcred
    schedule: "* * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure