jobs:
  # first cron
  - name: laqn
    image:
      repository: cleanairdocker.azurecr.io/laqn
      tag: 37cd09d53e7feb410f14a6fd408dfb6cc1398042
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: db-secrets

  - name: aqe
    image:
      repository: cleanairdocker.azurecr.io/aqe
      tag: 37cd09d53e7feb410f14a6fd408dfb6cc1398042
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: db-secrets

  - name: scoot
    image:
      repository: cleanairdocker.azurecr.io/scoot
      tag: 37cd09d53e7feb410f14a6fd408dfb6cc1398042
      imagePullPolicy: Always
    schedule: "0 * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumes:
    - name: secrets
      secret:
        secretName: db-secrets
    - name: secrets2
      secret:
        secretName: aws-secrets
