# This is a YAML-formatted file.
# Variables to be passed into the templates.
imageTag: 089bacc2ec600659d20ceb61f4900e5c28442114

cronjobs:

  - name: input-aqe
    schedule: "5 * * * *"
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
    failedJobsHistoryLimit: 10
    image:
        repository: cleanair
        imagePullPolicy: Never
        tag: local
    args: ["urbanair", "--secretfile", "db_secrets.json", "inputs", "aqe", "fill", "--ndays", "2"]
    volumeMounts:
    - name: secrets
      mountPath: "/secrets/"
      readOnly: true
    volumes:
    - name: secrets
      secret:
        secretName: secrets
    imagePullSecrets:
        - name: regcred
  
  - name: input-laqn
    schedule: "5 * * * *"
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
    failedJobsHistoryLimit: 10
    image:
        repository: cleanair
        imagePullPolicy: Never
        tag: local
    args: ["urbanair", "--secretfile", "db_secrets.json", "inputs", "laqn", "fill", "--ndays", "2"]
    volumeMounts:
    - name: secrets
      mountPath: "/secrets/"
      readOnly: true
    volumes:
    - name: secrets
      secret:
        secretName: secrets
    imagePullSecrets:
        - name: regcred

  - name: input-satellite
    schedule: "5 * * * *"
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
    failedJobsHistoryLimit: 10
    image:
        repository: cleanair
        imagePullPolicy: Never
        tag: local
    args: ["urbanair", "--secretfile", "db_secrets.json", "inputs", "satellite", "fill", "--ndays", "2", "--insert-method", "missing"]
    volumeMounts:
    - name: secrets
      mountPath: "/secrets/"
      readOnly: true
    volumes:
    - name: secrets
      secret:
        secretName: secrets
    imagePullSecrets:
        - name: regcred

  - name: input-scoot
    schedule: "5 * * * *"
    concurrencyPolicy: Allow
    restartPolicy: OnFailure
    failedJobsHistoryLimit: 10
    image:
        repository: cleanair
        imagePullPolicy: Never
        tag: local
    args: ["urbanair", "--secretfile", "db_secrets.json", "inputs", "scoot", "fill", "--ndays", "1"]
    volumeMounts:
    - name: secrets
      mountPath: "/secrets/"
      readOnly: true
    volumes:
    - name: secrets
      secret:
        secretName: secrets
    imagePullSecrets:
        - name: regcred

development: true