#! /usr/bin/env python
"""GP JAX Models CLI"""
from curses import echo
import importlib
import typer
from gpjax_models.parser import dataset, model

app = typer.Typer()
app.add_typer(dataset.app, name="dataset")
app.add_typer(model.app, name="model")
# app.add_typer(visualization.app, name="visualization")
if __name__ == "__main__":
    app()
