language: python

branches:
  only:
  - docker_build

services:
  - docker

before_install:
  - docker build -t CleanAirTestContainerRegistry/laqn:latest .

deploy:
  provider: script
  script: bash docker_push
