language: python

# branches:
#   only:
#   - master

services:
  - docker

script:
  - docker build -t cleanairtestcontainerregistry.azurecr.io/laqn:latest scripts/datasources/laqn/.

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

    