language: python

install:
  - pip install -r containers/requirements.txt

script:
  # # Run all pytest unit tests
  # - python -m pytest -v tests --cov containers --cov-report term-missing

  # Flake8 performs pyflakes, pycodestyle and McCabe complexity checks
  - flake8 --ignore=E203, W503

  # Check black formatting would not make any chages
  - black --check */

  # Run pylint for stricter error checking
  - pylint */
