language: python
python:
  - "3.8"
cache: pip

addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11-postgis-3
      - postgresql-11-postgis-3-scripts

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "cleanair"

      before_install:
        - sh .travis/before_install.sh
        - source .travis/env.sh

      install:
        - pip install -r containers/requirements.txt --use-deprecated=backtrack-on-build-failures
        - pip install -e 'containers/cleanair[geo]'

      before_script:
        - sh .travis/before_script.sh

      script:
        # Run all pytest unit tests
        - python -m pytest containers/tests/test_database_init --secretfile $DB_SECRET_FILE
        
        # see issue #786
        - python -m pytest containers/tests/test_cleanair --secretfile $DB_SECRET_FILE --ignore containers/tests/test_cleanair/test_models --ignore containers/tests/test_cleanair/test_experiment

        # Run pylint for stricter error checking
        - pylint --rcfile=.pylintrc */ --ignore=cleanair,urbanair,odysseus,tests
        # run linting for cleanair package without the models module
        - pylint --rcfile=.pylintrc --ignore=experiment,models,cleanair.egg-info,tf1 containers/cleanair/*
        # run linting for the tests but only detect warnings and errors
        - pylint --rcfile=.pylintrc --ignore test_models --disable=R,C containers/tests/test_cleanair/* containers/tests/test_database_init/*
        # Run type checking
        - mypy --config-file .mypy.ini containers/cleanair

    # separate parallel job for urbanair
    - name: "urbanair"
      before_install:
        - sh .travis/before_install.sh
        - source .travis/env.sh

      install:
        - pip install -r containers/requirements.txt  --use-deprecated=backtrack-on-build-failures
        - pip install -e 'containers/cleanair[geo]'
        - pip install -e 'containers/urbanair'

      before_script:
        - sh .travis/before_script.sh

      script:
        # Run all pytest unit tests
        - python -m pytest containers/tests/test_urbanair --secretfile $DB_SECRET_FILE

        # Run pylint for stricter error checking.
        # NB. We need to disable the hanging indentation check because of https://github.com/psf/black/issues/48
        - pylint --rcfile=.pylintrc containers/urbanair/* containers/tests/test_urbanair/*
        - mypy containers/urbanair

    - name: "code_style_formatting"
      install:
        - pip install -r containers/requirements.txt  --use-deprecated=backtrack-on-build-failures

      script:
        # Check black formatting would not make any chages
        - black --check */
        # Flake8 performs pyflakes, pycodestyle and McCabe complexity checks
        - flake8 --ignore=E203, W503
