language: python

branches:
  only:
  - docker_build

services:
  - docker

before_install:
  - docker build -t cleanairtestcontainerregistry.azurecr.io/laqn:latest scripts/datasources/laqn/.
  - docker push cleanairtestcontainerregistry.azurecr.io/laqn:latest

# deploy:
#   provider: script
#   script: bash docker_push
