language: python

services:
  - docker

script:
  # # Run all pytest unit tests
  # - python -m pytest -v tests --cov misinformation --cov-report term-missing
  # Run pyflakes for error detection
  - pyflakes *.py scripts #tests
  # Check PEP8 compliance (ignoring long lines)
  - pycodestyle --statistics --ignore=E501 --count *.py scripts #tests
  # Run pylint for stricter error checking
  - pylint *py scripts/datasources/* #tests

 # Ensure we build every docker image

  # Datasources
  - docker build -t $ACR_SERVER/laqn:$TRAVIS_PULL_REQUEST_SHA -f scripts/datasources/laqn.Dockerfile scripts/datasources/. 
  - docker build -t $ACR_SERVER/aqe:$TRAVIS_PULL_REQUEST_SHA -f scripts/datasources/aqe.Dockerfile scripts/datasources/.
  # - docker build -t "$ACR_SERVER"/darksky:$TRAVIS_PULL_REQUEST_SHA scripts/datasources/darksky/.
  # - docker build -t "$ACR_SERVER"/ECMWF:$TRAVIS_PULL_REQUEST_SHA scripts/datasources/ECMWF/.

  # Static datasources
  - docker build -t $ACR_SERVER/insert_static_datasource:latest scripts/datasources/static/.

  # Push to ACR
  - bash docker_push.sh

