language: python
python:
  - "3.7"
cache: pip

addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11-postgis-3
      - postgresql-11-postgis-3-scripts

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "cleanair"

      before_install:
        - sh .travis/before_install.sh
        - source .travis/env.sh

      install:
        - pip install -r containers/requirements.txt
        - pip install -e 'containers/cleanair[models,traffic,dashboard]'
        - pip install -e 'containers/urbanair'

      before_script:
        - sh .travis/before_script.sh

      script:
        # Run all pytest unit tests
        - python -m pytest containers/tests/test_cleanair --secretfile $DB_SECRET_FILE
        - python -m pytest containers/tests/test_database_init --secretfile $DB_SECRET_FILE

        # Run pylint for stricter error checking
        # NB. We need to disable the hanging indentation check because of https://github.com/psf/black/issues/48
        - pylint --rcfile=.pylintrc */ --ignore=cleanair,urbanair,odysseus,tests
        # run linting for cleanair package without the mrdgp module
        - pylint --rcfile=.pylintrc --ignore=mr_dgp,cleanair.egg-info containers/cleanair/*
        # run linting for the mrdgp module but only detect warnings and errors
        - pylint --rcfile=.pylintrc --disable=R,C containers/cleanair/cleanair/models/mr_dgp/*
        # run linting for the tests but only detect warnings and errors
        - pylint --rcfile=.pylintrc --disable=R,C containers/tests/test_cleanair/* containers/tests/test_database_init/*
        # Run type checking
        - mypy --config-file .mypy.ini containers/cleanair
  
    # separate parallel job for odysseus
    - name: "odysseus"
      before_install:
        - sh .travis/before_install.sh
        - source .travis/env.sh

      install:
        - pip install -r containers/requirements.txt
        - pip install -e 'containers/cleanair'
        - pip install -e 'containers/odysseus'

      before_script:
        - sh .travis/before_script.sh

      script:
        # Run all pytest unit tests
        - python -m pytest containers/tests/test_odysseus --secretfile $DB_SECRET_FILE

        # Run pylint for stricter error checking.
        # NB. We need to disable the hanging indentation check because of https://github.com/psf/black/issues/48
        - pylint --rcfile=.pylintrc containers/odysseus/* containers/tests/test_odysseus/*

    # separate parallel job for urbanair
    - name: "urbanair"
      before_install:
        - sh .travis/before_install.sh
        - source .travis/env.sh

      install:
        - pip install -r containers/requirements.txt
        - pip install -e 'containers/cleanair'
        - pip install -e 'containers/urbanair'

      before_script:
        - sh .travis/before_script.sh

      script:
        # Run all pytest unit tests
        - python -m pytest containers/tests/test_urbanair --secretfile $DB_SECRET_FILE

        # Run pylint for stricter error checking.
        # NB. We need to disable the hanging indentation check because of https://github.com/psf/black/issues/48
        - pylint --rcfile=.pylintrc containers/urbanair/* containers/tests/test_urbanair/*
        - mypy containers/urbanair

    - name: "code_style_formatting"
      install:
        - pip install -r containers/requirements.txt

      script:
        # Check black formatting would not make any chages
        - black --check */
        # Flake8 performs pyflakes, pycodestyle and McCabe complexity checks
        - flake8 --ignore=E203, W503
