language: python

services:
  - docker

script:
  # # Run all pytest unit tests
  # - python -m pytest -v tests --cov misinformation --cov-report term-missing
  # Run pyflakes for error detection
  - pyflakes *.py scripts #tests
  # Check PEP8 compliance (ignoring long lines)
  - pycodestyle --statistics --ignore=E501 --count *.py scripts #tests
  # Run pylint for stricter error checking
  - pylint scripts/datasources/* #tests

  # Build docker images
  - docker build -t cleanaircontainerregistry.azurecr.io/laqn:latest scripts/datasources/laqn/.


deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

