language: python

services:
  - docker

script:
  # # Run all pytest unit tests
  # - python -m pytest -v tests --cov misinformation --cov-report term-missing

  # Run pyflakes for error detection
  - pyflakes **/*.py

  # Check PEP8 compliance (ignoring long lines)
  - pycodestyle --statistics --ignore=R0801 --max-line-length=120 --count **/*.py

  # Run pylint for stricter error checking
  - pylint **/*.py

  # Build all docker images
  - docker build -t $ACR_SERVER/aqe:$TRAVIS_PULL_REQUEST_SHA -f docker/dockerfiles/update_aqe_database.Dockerfile containers/.
  - docker build -t $ACR_SERVER/laqn:$TRAVIS_PULL_REQUEST_SHA -f docker/dockerfiles/update_laqn_database.Dockerfile containers/.
  - docker build -t $ACR_SERVER/scoot:$TRAVIS_PULL_REQUEST_SHA -f docker/dockerfiles/update_scoot_database.Dockerfile containers/.
  - docker build -t $ACR_SERVER/static:$TRAVIS_PULL_REQUEST_SHA -f docker/dockerfiles/upload_static_dataset.Dockerfile containers/.

  # Push all our docker images to the container registry
  - echo "$ACR_PASSWORD" | docker login -u "$ACR_USERNAME" --password-stdin "$ACR_SERVER"
  - docker push $ACR_SERVER/aqe:$TRAVIS_PULL_REQUEST_SHA
  - docker push $ACR_SERVER/laqn:$TRAVIS_PULL_REQUEST_SHA
  - docker push $ACR_SERVER/scoot:$TRAVIS_PULL_REQUEST_SHA
  - docker push $ACR_SERVER/static:$TRAVIS_PULL_REQUEST_SHA
