services:
  - docker
  - postgresql

before_install:
  - echo $SAS_TOKEN
  - psql -c 'create database cleanair_test_db' -U postgres
  - | 
      mkdir -p .secrets
      echo '{
          "username": "postgres",
          "password": "''",
          "host": "host.docker.internal",
          "port": 5432,
          "db_name": "cleanair_test_db",
          "ssl_mode": "prefer"
      }' >> .secrets/db_secrets_offline.json
  
  - docker build -t insert_static_data:latest -f containers/dockerfiles/process_static_dataset.Dockerfile "containers"  
  - docker run  -v $(pwd)/.secrets:/secrets insert_static_data:latest -t $SAS_TOKEN -s db_secrets_offline.json -d street_canyon

language: python
python:
  - "3.7"

install:
  - pip install -r containers/requirements.txt
  - pip install 'containers/cleanair[models,traffic,dashboard]'
  - pip install 'containers/uatraffic'

script:
  # # Run all pytest unit tests
  # - python -m pytest -v tests --cov containers --cov-report term-missing

  # Flake8 performs pyflakes, pycodestyle and McCabe complexity checks
  - flake8 --ignore=E203, W503

  # Check black formatting would not make any chages
  - black --check */

  # Run pylint for stricter error checking. Run for each package seperately and then run for everything else
  # NB. We need to disable the hanging indentation check because of https://github.com/psf/black/issues/48
  - pylint --disable=C0330 */ --ignore=cleanair,urbanair,uatraffic
  - pylint --disable=C0330 containers/cleanair/*
  # - pylint --disable=C0330 containers/urbanair/*
  - pylint --disable=C0330 containers/uatraffic/*
