language: python

services:
  - docker

script:
  - docker build -t cleanaircontainerregistry.azurecr.io/laqn:$TRAVIS_PULL_REQUEST_SHA scripts/datasources/laqn/.
  - docker push cleanaircontainerregistry.azurecr.io/laqn:$TRAVIS_PULL_REQUEST_SHA

  

    