language: python
python:
  - "3.7"
cache: pip

addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11-postgis-3
      - postgresql-11-postgis-3-scripts

jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "cleanair" 
      before_install:
        - sh .travis/before_install.sh

      install:
        - pip install -r containers/requirements.txt
        - pip install 'containers/cleanair[models,traffic,dashboard]'

      before_script:
        - sh .travis/before_script.sh

      script:
        - sh .travis/test_cleanair.sh
    # separate parallel job for odysseus
    - name: "odysseus" 
      before_install:
        - sh .travis/before_install.sh

      install:
        - pip install -r containers/requirements.txt
        - pip install 'containers/cleanair'
        - pip install 'containers/odysseus'

      before_script:
        - sh .travis/before_script.sh

      script:
        - sh .travis/test_odysseus.sh