addons: 
  postgresql: "11"

before_script:
  - psql -c 'create database cleanair_tests_db' -U postgres

language: python
python:
  - "3.7"

install:
  - pip install -r containers/requirements.txt
  - pip install 'containers/cleanair[models,traffic,dashboard]'
  - pip install 'containers/uatraffic'

script:
  # # Run all pytest unit tests
  # - python -m pytest -v tests --cov containers --cov-report term-missing

  # Flake8 performs pyflakes, pycodestyle and McCabe complexity checks
  - flake8 --ignore=E203, W503

  # Check black formatting would not make any chages
  - black --check */

  # Run pylint for stricter error checking. Run for each package seperately and then run for everything else
  # NB. We need to disable the hanging indentation check because of https://github.com/psf/black/issues/48
  - pylint --disable=C0330 */ --ignore=cleanair,urbanair,uatraffic
  - pylint --disable=C0330 containers/cleanair/*
  # - pylint --disable=C0330 containers/urbanair/*
  - pylint --disable=C0330 containers/uatraffic/*
