trigger:
- master

pr: none

variables:
  namespace: "cleanair"
  helm_release: "cleanair"
  kubernetes_cluster_name: "cleanair-kubernetes"
  kubernetes_cluster_resource_group: "RG_CLEANAIR_KUBERNETES_CLUSTER"

stages:
- stage: Docker
  displayName: Add new Docker images to ACR
  jobs:
  - job: BuildAndPushDocker
    displayName: Build and register Docker images
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureKeyVault@1
      displayName: 'Read KeyVault secrets'
      inputs:
        azureSubscription: 'cleanair-scn'
        KeyVaultName: 'cleanair-secrets'
        SecretsFilter: 'container-registry-admin-password,container-registry-admin-username,container-registry-login-server'
    # Build AQE
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/aqe:$(Build.SourceVersion) -f containers/dockerfiles/add_aqe_readings.Dockerfile containers
      displayName: 'Build AQE data collection image'
    # Build LAQN
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/laqn:$(Build.SourceVersion) -f containers/dockerfiles/add_laqn_readings.Dockerfile containers
      displayName: 'Build LAQN data collection image'
    # Build SCOOT
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/scoot:$(Build.SourceVersion) -f containers/dockerfiles/add_scoot_readings.Dockerfile containers
      displayName: 'Build SCOOT data collection image'
    # Build SCOOT road maps
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/scoot-roadmap:$(Build.SourceVersion) -f containers/dockerfiles/construct_scoot_roadmaps.Dockerfile containers
      displayName: 'Build SCOOT road mapping image'
    # Build SCOOT forecast features
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/scootforecastfeatures:$(Build.SourceVersion) -f containers/dockerfiles/features_scoot_forecasts.Dockerfile containers
      displayName: 'Build SCOOT forecast features image'
    # Build SCOOT reading features
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/scootreadingfeatures:$(Build.SourceVersion) -f containers/dockerfiles/features_scoot_readings.Dockerfile containers
      displayName: 'Build SCOOT reading features image'
    # Build satellite
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/satellite:$(Build.SourceVersion) -f containers/dockerfiles/add_satellite_readings.Dockerfile containers
      displayName: 'Build satellite data collection image'
    # Build OSHighway
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/oshighway:$(Build.SourceVersion) -f containers/dockerfiles/extract_oshighway_features.Dockerfile containers
      displayName: 'Build OSHighway feature processing image'
    # Build Street Canyon
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/streetcanyon:$(Build.SourceVersion) -f containers/dockerfiles/extract_streetcanyon_features.Dockerfile containers
      displayName: 'Build street canyon feature processing image'
    # Build UKMap
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/ukmap:$(Build.SourceVersion) -f containers/dockerfiles/extract_ukmap_features.Dockerfile containers
      displayName: 'Build UKMap feature processing image'
    # Build extract SCOOT
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)extract_scoot:$(Build.SourceVersion) -f containers/dockerfiles/extract_scoot_features.Dockerfile containers
      displayName: 'Build scoot feature processing image'
    # Build API
    - script: |
        docker build -t $(CONTAINER-REGISTRY-LOGIN-SERVER)/cleanairapi:$(Build.SourceVersion) -f containers/dockerfiles/cleanairapi.Dockerfile containers
      displayName: 'Build cleanair feature processing image'
    # List available images
    - script: |
        docker images
      displayName: 'List images'
    # Login to ACR
    - script: |
        echo "$(CONTAINER-REGISTRY-ADMIN-PASSWORD)" | docker login -u "$(CONTAINER-REGISTRY-ADMIN-USERNAME)" --password-stdin "$(CONTAINER-REGISTRY-LOGIN-SERVER)"
      displayName: 'Login to ACR'
    # Push Docker images to ACR
    - script: |
        docker push $(CONTAINER-REGISTRY-LOGIN-SERVER)/aqe:$(Build.SourceVersion)
        docker push $(CONTAINER-REGISTRY-LOGIN-SERVER)/laqn:$(Build.SourceVersion)
        docker push $(CONTAINER-REGISTRY-LOGIN-SERVER)/scoot:$(Build.SourceVersion)
        docker push $(CONTAINER-REGISTRY-LOGIN-SERVER)/scootforecast:$(Build.SourceVersion)
        docker push $(CONTAINER-REGISTRY-LOGIN-SERVER)/oshighway:$(Build.SourceVersion)
        docker push $(CONTAINER-REGISTRY-LOGIN-SERVER)/streetcanyon:$(Build.SourceVersion)
        docker push $(CONTAINER-REGISTRY-LOGIN-SERVER)/ukmap:$(Build.SourceVersion)
        docker push $(CONTAINER-REGISTRY-LOGIN-SERVER)/cleanairapi:$(Build.SourceVersion)
        docker push $(CONTAINER-REGISTRY-LOGIN-SERVER)/satellite:$(Build.SourceVersion)
      displayName: 'Push Docker images to ACR'

- stage: Kubernetes
  displayName: Update Helm chart on Azure Kubernetes cluster
  jobs:
  - job: UpdateAzureKubernetesHelmChart
    displayName: Install Kubectl and install/upgrade helm
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Connect to Azure
    - task: AzureCLI@1
      displayName: 'Connect to Azure'
      inputs:
        azureSubscription: 'cleanair-scn'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials -n $(KUBERNETES_CLUSTER_NAME) -g $(KUBERNETES_CLUSTER_RESOURCE_GROUP)
          KUBERNETES_VERSION=$(az aks show -n $(KUBERNETES_CLUSTER_NAME) -g $(KUBERNETES_CLUSTER_RESOURCE_GROUP) --query "kubernetesVersion" -o tsv)
          echo "##vso[task.setvariable variable=kubernetes_version]$KUBERNETES_VERSION"
    # Read Azure key vault
    - task: AzureKeyVault@1
      displayName: 'Read KeyVault secrets'
      inputs:
        azureSubscription: 'cleanair-scn'
        KeyVaultName: 'cleanair-secrets'
        SecretsFilter: 'scoot-aws-key,scoot-aws-key-id,cleanair-inputs-db-name,cleanair-inputs-db-admin-password,cleanair-inputs-db-admin-username,cleanair-inputs-db-server-name,container-registry-admin-password,container-registry-admin-username,container-registry-login-server'
    # Install matching Kubectl version
    - task: KubectlInstaller@0
      displayName: 'Install matching Kubectl version'
      inputs:
        kubectlVersion: $(KUBERNETES_VERSION)
    # Install latest Helm version
    - task: HelmInstaller@1
      displayName: 'Install latest Helm version'
      inputs:
        helmVersionToInstall: latest
    # List installed versions
    - script: |
        echo "Kubernetes version on the cluster is ${KUBERNETES_VERSION}"
        echo "Kubectl details:"
        kubectl version
        echo "Helm details:"
        helm version
        echo "Helm $(NAMESPACE) namespace:"
        helm list --namespace $(NAMESPACE)
      displayName: 'List installed versions'
    # Add secrets to Kubernetes
    - script: |
        echo "Adding secrets to Kubernetes"
        if [ "$(kubectl get secret regcred --namespace cleanair 2> /dev/null | grep regcred)" == "" ]; then
          kubectl create secret docker-registry --namespace cleanair regcred --docker-server=$(CONTAINER-REGISTRY-LOGIN-SERVER) --docker-username=$(CONTAINER-REGISTRY-ADMIN-USERNAME) --docker-password=$(CONTAINER-REGISTRY-ADMIN-PASSWORD)
        fi
        if [ "$(kubectl get secret secrets --namespace cleanair 2> /dev/null | grep secrets)" == "" ]; then
          echo  '{
            "aws_key_id": "$(SCOOT-AWS-KEY-ID)",
            "aws_key": "$(SCOOT-AWS-KEY)"
          }' > aws_secrets.json
          echo '{
            "username": "$(CLEANAIR-INPUTS-DB-ADMIN-USERNAME)@$(CLEANAIR-INPUTS-DB-SERVER-NAME)",
            "password": "$(CLEANAIR-INPUTS-DB-ADMIN-PASSWORD)",
            "host": "$(CLEANAIR-INPUTS-DB-SERVER-NAME).postgres.database.azure.com",
            "port": 5432,
            "db_name": "$(CLEANAIR-INPUTS-DB-NAME)",
            "ssl_mode": "require"
          }' > db_secrets.json
          kubectl create secret generic --namespace cleanair secrets --from-file=aws_secrets.json --from-file=db_secrets.json
          rm -f aws_secrets.json db_secrets.json
          # kubectl create secret generic --namespace cleanair secrets --from-literal=host='$(CLEANAIR-INPUTS-DB-SERVER-NAME).postgres.database.azure.com' --from-literal=port=5432 --from-literal=db_name='$(CLEANAIR-INPUTS-DB-NAME)' --from-literal=username='$(CLEANAIR-INPUTS-DB-ADMIN-USERNAME)@$(CLEANAIR-INPUTS-DB-SERVER-NAME)' --from-literal=password='$(CLEANAIR-INPUTS-DB-ADMIN-PASSWORD)' --from-literal=ssl_mode='require' --from-literal=aws_key_id='$(SCOOT-AWS-KEY-ID)' --from-literal=aws_key='$(SCOOT-AWS-KEY)'
        fi
      displayName: 'Add secrets to Kubernetes'
    # Prepare Helm chart
    - script: |
        # Check whether we need to create a new namespace
        if [ "$(kubectl get namespace $(NAMESPACE) 2> /dev/null | grep $(NAMESPACE))" == "" ]; then
          kubectl create namespace $(NAMESPACE)
        fi
        echo "Setting image tag to $(Build.SourceVersion)"
        sed -i 's/^imageTag:.*$/imageTag: $(Build.SourceVersion)/' kubernetes/cleanair/values.yaml
      displayName: 'Prepare Helm chart'
    # Install/upgrade Helm chart
    - task: HelmDeploy@0
      displayName: 'Install/upgrade Helm chart'
      inputs:
        connectionType: Azure Resource Manager
        azureSubscriptionEndpoint: 'cleanair-scn'
        azureResourceGroup: $(KUBERNETES_CLUSTER_RESOURCE_GROUP)
        kubernetesCluster: $(KUBERNETES_CLUSTER_NAME)
        namespace: $(NAMESPACE)
        command: upgrade
        arguments: --cleanup-on-fail
        chartType: filepath
        chartPath: kubernetes/cleanair
        releaseName: cleanair
        install: true
