#!/usr/bin/env python

import typer
from cleanair.parsers.urbanair_parser import config, init, inputs, features, model

app = typer.Typer(callback=init.init_callback)
app.add_typer(config.app, name="config")
app.add_typer(init.app, name="init")
app.add_typer(inputs.app, name="inputs")
app.add_typer(features.app, name="features")
app.add_typer(model.app, name="model")

if __name__ == "__main__":
    app()
