#!/usr/bin/env python

import typer
from cleanair.parsers.urbanair_parser import config, init, inputs, features

app = typer.Typer(callback=init.init_app)
app.add_typer(config.app, name="config")
app.add_typer(init.app, name="init")
app.add_typer(inputs.app, name="inputs")
app.add_typer(features.app, name="features")

if __name__ == "__main__":
    app()
