#! /usr/bin/env python
"""UrbanAir CLI"""

import typer
from cleanair.parsers.urbanair_parser import (
    config,
    experiment,
    init,
    inputs,
    features,
    model,
    processors,
)

app = typer.Typer(callback=init.init_callback)
app.add_typer(config.app, name="config")
app.add_typer(experiment.app, name="experiment")
app.add_typer(init.app, name="init")
app.add_typer(inputs.app, name="inputs")
app.add_typer(features.app, name="features")
app.add_typer(model.app, name="model")
app.add_typer(processors.app, name="processors")

if __name__ == "__main__":
    app()
