"""Parameters for cleanair models."""

from .shared_params import (
    LENGTHSCALES,
    LIKELIHOOD_VARIANCE,
    KERNEL_VARIANCE,
    MINIBATCH_SIZE,
    PRODUCTION_BUFFER_SIZES,
    PRODUCTION_DYNAMIC_FEATURES,
    PRODUCTION_FORECAST_DAYS,
    PRODUCTION_STATIC_FEATURES,
)
from .svgp_params import (
    default_svgp_kernel,
    default_svgp_model_params,
    JITTER,
    PRODUCTION_SVGP_TRAIN_DAYS,
    PRODUCTION_SVGP_FORECAST_INTEREST_POINTS,
    PRODUCTION_SVGP_FORECAST_SOURCES,
    PRODUCTION_SVGP_SPECIES,
    PRODUCTION_SVGP_TRAIN_INTEREST_POINTS,
    PRODUCTION_SVGP_TRAIN_SOURCES,
    SVGP_NUM_INDUCING_POINTS,
    SVGP_MAXITER,
)

__all__ = [
    "default_svgp_kernel",
    "default_svgp_model_params",
    "JITTER",
    "LENGTHSCALES",
    "LIKELIHOOD_VARIANCE",
    "KERNEL_VARIANCE",
    "MINIBATCH_SIZE",
    "PRODUCTION_BUFFER_SIZES",
    "PRODUCTION_DYNAMIC_FEATURES",
    "PRODUCTION_FORECAST_DAYS",
    "PRODUCTION_STATIC_FEATURES",
    "PRODUCTION_SVGP_TRAIN_DAYS",
    "PRODUCTION_SVGP_FORECAST_INTEREST_POINTS",
    "PRODUCTION_SVGP_FORECAST_SOURCES",
    "PRODUCTION_SVGP_SPECIES",
    "PRODUCTION_SVGP_TRAIN_INTEREST_POINTS",
    "PRODUCTION_SVGP_TRAIN_SOURCES",
    "SVGP_NUM_INDUCING_POINTS",
    "SVGP_MAXITER",
]
