# Project information
site_name: Urbanair
site_description: Documentation for the UrbanAir project
site_author: Oscar Giles etc
site_url: https://urbanair.turing.ac.uk/docs

# Repository
repo_name: alan-turing-institute/clean-air-infrastructure
repo_url: https://github.com/alan-turing-institute/clean-air-infrastructure

# Copyright
copyright: Copyright &copy; 2019-2020 Alan Turing Institute

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/alan-turing-institute/clean-air-infrastructure
    - icon: fontawesome/brands/twitter
      link: https://www.turing.ac.uk/research/research-projects/london-air-quality

# Google Analytics
google_analytics:
  - UA-XXXXXXXX-X
  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - containers/cleanair
        - containers/odysseus

nav:
- Cleanair: index.md
- User Guide:
  - Setting up a developmet environment:
    - setup/azure-account.md
    - setup/non-infrastructure-dependencies.md
    - setup/infrastructure-dependencies.md
    - setup/configure-local-database.md
  
  - accessing-production-database.md
  - entry-points.md
  - urbanair-api.md
  - developer-guide.md
  - researcher-guide.md
  - infrastructure-development.md 
  

- API: 
  - Cleanair: 
    - API/cleanair/dashboard.md
    - API/cleanair/databases.md
    - API/cleanair/decorators.md
    - API/cleanair/features.md
    - API/cleanair/inputs.md
    - API/cleanair/instance.md
    - API/cleanair/loggers.md
    - API/cleanair/metrics.md
    - API/cleanair/mixins.md
    - API/cleanair/models.md
    - API/cleanair/parsers.md
    - API/cleanair/timestamps.md
  - Odysseus:
    - API/odysseus/databases.md
    - API/odysseus/test_types.md
    - API/odysseus/dates.md
    - API/odysseus/metric.md
    - API/odysseus/parsers.md
    - API/odysseus/preprocess.md
    - API/odysseus/scoot_processing.md
