#! /usr/bin/env python
"""UrbanAir CLI"""
from curses import echo
import importlib
import typer
from cleanair_data.parsers.urbanair_parser import (
    # config,
    # echo,
    # experiment,
    init,
    # inputs,
    # logs,
    # features,
    # metrics,
    dataset,
    # model,
    # production,
)

# TODO re-add the experiment & model apps

has_prophet = importlib.util.find_spec("fbprophet")
has_pystan = importlib.util.find_spec("pystan")

app = typer.Typer()
# app.add_typer(config.app, name="config")
app.add_typer(dataset.app, name="dataset")
# app.add_typer(echo.app, name="echo")
# # app.add_typer(experiment.app, name="experiment")
app.add_typer(init.app, name="init")
# app.add_typer(inputs.app, name="inputs")
# app.add_typer(logs.app, name="logs")
# app.add_typer(features.app, name="features")
# app.add_typer(metrics.app, name="metrics")
# app.add_typer(model.app, name="model")
# app.add_typer(production.app, name="production")

if has_prophet and has_pystan:
    from cleanair_data.parsers.urbanair_parser import processors

    app.add_typer(processors.app, name="processors")

if __name__ == "__main__":
    app()
