# Project information
site_name: CleanAir Development Docs
site_description: Documentation for the CleanAir project
site_author: Oscar Giles, James Robinson, Patrick O'Hara, Christy Nakou, David Pérez-Suárez, Tim Spain
site_url: https://urbanair.turing.ac.uk/dev/docs

# Repository
repo_name: alan-turing-institute/clean-air-infrastructure
repo_url: https://github.com/alan-turing-institute/clean-air-infrastructure

# Copyright
copyright: Copyright &copy; 2019-2020 Alan Turing Institute

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/alan-turing-institute/clean-air-infrastructure
    - icon: fontawesome/brands/twitter
      link: https://www.turing.ac.uk/research/research-projects/london-air-quality

# Google Analytics
google_analytics:
  - UA-XXXXXXXX-X
  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - containers/cleanair

docs_dir: 'docs_src/'
nav:
  - Cleanair: index.md
  - Developer setup:
    - setup/azure-account.md
    - setup/non-infrastructure-dependencies.md
    - setup/infrastructure-dependencies.md
    - Databases:
      - setup/configure-local-database.md
      - setup/accessing-production-database.md
  - Style and tests:
    - developer_guide/style-guide.md
    - developer_guide/tests.md
  - CleanAir:
    - cleanair/cleanair-cli.md
  - UrbanAir API:
    - urbanair-api.md
  - Infrastructure:
    - infrastructure/infrastructure-deployment.md
  - researcher-guide.md

# ToDo: Add API docs
# - API: 
#   - Cleanair: 
#     - API/cleanair/dashboard.md
#     - API/cleanair/databases.md
#     - API/cleanair/decorators.md
#     - API/cleanair/features.md
#     - API/cleanair/inputs.md
#     - API/cleanair/instance.md
#     - API/cleanair/loggers.md
#     - API/cleanair/metrics.md
#     - API/cleanair/models.md
#     - API/cleanair/parsers.md
#     - API/cleanair/timestamps.md
