<<<<<<< HEAD

{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $tag := .Values.imageTag }}

{{- range $deployment := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $release_name }}-{{ $deployment.name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
    app: "{{ $release_name }}-{{ $deployment.name }}"
spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ $release_name }}-{{ $deployment.name }}"
  template:
    metadata:
      labels:
        app: "{{ $release_name }}-{{ $deployment.name }}"
    spec:
        containers:
        - image: "{{ $deployment.image.repository }}:{{ $tag }}"
          imagePullPolicy: {{ $deployment.image.imagePullPolicy }}            
          name: "{{ $release_name }}-{{ $deployment.name }}"
          ports:
            - containerPort: {{ $deployment.ports.containerPort }}
          {{- with $deployment.volumeMounts }}
          volumeMounts:
{{ toYaml . | indent 10 }}
        {{- end }}
        imagePullSecrets:
        - name: regcred
        restartPolicy: {{ $deployment.restartPolicy }}
        {{- with $deployment.volumes }}
        volumes:
{{ toYaml . | indent 8 }}
        {{- end }}
{{- end }}
=======

{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $tag := .Values.imageTag }}

{{- range $deployment := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $release_name }}-{{ $deployment.name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
    app: "{{ $release_name }}-{{ $deployment.name }}"
spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ $release_name }}-{{ $deployment.name }}"
  template:
    metadata:
      labels:
        app: "{{ $release_name }}-{{ $deployment.name }}"
    spec:
        containers:
        - image: "{{ $deployment.image.repository }}:{{ $tag }}"
          imagePullPolicy: {{ $deployment.image.imagePullPolicy }}            
          name: "{{ $release_name }}-{{ $deployment.name }}"
          ports:
            - containerPort: {{ $deployment.ports.containerPort }}
          {{- with $deployment.volumeMounts }}
          volumeMounts:
{{ toYaml . | indent 10 }}
        {{- end }}
        imagePullSecrets:
        - name: regcred
        restartPolicy: {{ $deployment.restartPolicy }}
        {{- with $deployment.volumes }}
        volumes:
{{ toYaml . | indent 8 }}
        {{- end }}
        {{- with $deployment.nodeSelector }}
        nodeSelector:
{{ toYaml . | indent 8 }}
        {{- end }}
{{- end }}
>>>>>>> 566626e3b8beb34ade921a178a3b33a981c759c5
