
{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

{{- range $deployment := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  metadata:
  name: "{{ $release_name }}-{{ $deployment.name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"


{{- end }}