
{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $tag := .Values.imageTag }}
{{ if .Values.ingressRules}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    {{- range $tls := .Values.tls }}
    - {{ $tls.host }}
    {{- end }}
    secretName: tls-secret
  rules:
  {{- range $rule := .Values.ingressRules }}
  - host: {{ $rule.host }}
    http:
      paths:
      {{- range $path := $rule.paths }}
      - path: {{ $path.path }}
        backend:
          serviceName: "{{ $release_name }}-{{ $path.serviceName }}"
          servicePort: {{ $path.servicePort }}
      {{- end }}
  {{- end }}
{{ end }}