
{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $tag := .Values.imageTag }}
{{- $issueType := .Values.letsencryptType }}
{{ if .Values.ingressRules}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/issuer: "letsencrypt-{{ $issueType }}"
    {{- if $.Values.whitelistSourceRange}}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ $.Values.whitelistSourceRange }}
    {{ end }}
spec:
  tls:
  - hosts:
    {{- range $tls := .Values.tls }}
    - {{ $tls.host }}
    secretName: {{ $tls.secretName }}
    {{- end }}
  rules:
  {{- range $rule := .Values.ingressRules }}
  - host: {{ $rule.host }}
    http:
      paths:
      {{- range $path := $rule.paths }}
      - path: {{ $path.path }}
        backend:
          serviceName: "{{ $release_name }}-{{ $path.serviceName }}"
          servicePort: {{ $path.servicePort }}
      {{- end }}
  {{- end }}
{{ end }}