<<<<<<< HEAD

{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $tag := .Values.imageTag }}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $release_name }}-{{ $job.name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
    template:
        spec:
            containers:
            - name: {{ $job.name }}
              image: "{{ $job.image.repository }}:{{ $tag }}"
              imagePullPolicy: {{ $job.image.imagePullPolicy }}
              volumeMounts:
               - name: secrets
                 mountPath: "/secrets/"
                 readOnly: true
              args: {{ $job.args }}
            imagePullSecrets:
            - name: regcred
            restartPolicy: {{ $job.restartPolicy }}

            {{- with $job.volumes }}
            volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
            {{- with $job.env }}
            env:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with $job.volumeMounts }}
            volumeMounts:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with $job.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
    
=======

{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $tag := .Values.imageTag }}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $release_name }}-{{ $job.name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
    template:
        spec:
            containers:
            - name: {{ $job.name }}
              {{- if $job.image.tag}}
              image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
              {{else}}
              image: "{{ $job.image.repository }}:{{ $tag }}"
              {{- end }}
              imagePullPolicy: {{ $job.image.imagePullPolicy }}
              {{- with $job.command }}
              command:
{{ toYaml . | indent 16 }}
              {{- end }}
              {{- with $job.args }}
              args:
{{ toYaml . | indent 16 }}     
              {{- end }}
              {{- with $job.resources }}
              resources:
{{ toYaml . | indent 16 }}
              {{- end }}

            {{- with $job.volumeMounts }}
              volumeMounts:
{{ toYaml . | indent 14 }}
            {{- end }}
            {{- with $job.imagePullSecrets }}
            imagePullSecrets:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with $job.volumes }}
            volumes:
{{ toYaml . | indent 12 }}
          {{- end }}
            {{- with $job.env }}
            env:
{{ toYaml . | indent 12 }}
            {{- end }}
            {{- with $job.nodeSelector }}
            nodeSelector:
{{ toYaml . | indent 14 }}
            {{- end }}
          {{- with $job.affinity }}
            affinity:
{{ toYaml . | indent 14 }}
          {{- end }}
          {{- with $job.tolerations }}
            tolerations:
{{ toYaml . | indent 14 }}
          {{- end }}
            restartPolicy: {{ $job.restartPolicy }}
    
>>>>>>> 566626e3b8beb34ade921a178a3b33a981c759c5
{{- end }}