{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $tag := .Values.imageTag }}

{{- range $service := .Values.services }}
---

apiVersion: v1
kind: Service
metadata:
  name: "{{ $release_name }}-{{ $service.name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
  type: {{ $service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: {{ $service.name }}

{{- end }}
