{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $tag := .Values.imageTag }}

{{- range $service := .Values.services }}
---

apiVersion: v1
kind: Service
metadata:
  name: "{{ $release_name }}-{{ $service.name }}"
  labels:
    chart: "{{ $chart_name }}-{{ $chart_version }}"
spec:
  type: {{ $service.type }}
  selector:
    app: "{{ $release_name }}-{{ $service.name }}"
  ports:
    {{- range $port := $service.ports}}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
    {{- end }}
  selector:
    app: "{{ $release_name }}-{{ $service.name }}"

{{- end }}
