#!/usr/bin/env python

import typer
from cleanair.parsers.urbanair_parser import config, init, inputs
from odysseus import parsers

app = typer.Typer(callback=init.init_callback, help="Project Odysseus")
app.add_typer(parsers.baseline_cli.app, name="baseline")
app.add_typer(config.app, name="config")
app.add_typer(parsers.forecast_cli.app, name="forecast")
app.add_typer(init.app, name="init")
app.add_typer(inputs.app, name="inputs")
app.add_typer(parsers.metrics_cli.app, name="metrics")
app.add_typer(parsers.scan_cli.app, name="scan")
app.add_typer(parsers.train_cli.app, name="train")

if __name__ == "__main__":
    app()
