apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the clean air microservice
name: cleanair
version: 0.1.0
home: https://github.com/alan-turing-institute/clean-air-infrastructure
sources: 
  - https://github.com/alan-turing-institute/clean-air-infrastructure
maintainers:
  - name: James Robinson
    email: jrobinson@turing.ac.uk
  - name: Oscar Giles 
    email: ogiles@turing.ac.uk
