apiVersion: batch/v1
kind: Job
metadata:
    name: jamcam-backfill-$ITEM
    namespace: jamcam-backfill
    labels:
      jobgroup: jamcam-backfill
spec:
    template:
      spec:
        containers:
        - name: jamcam-backfill-$ITEM
          image:  cleanairdocker.azurecr.io/traffic/tfl_traffic_analysis:latest
          imagePullPolicy: Always
          command: ["bash", "/application/deployscripts/cluster.sh"]
          args: ["-dH", "$ITEM"]
          volumeMounts:
          - name: secrets
            mountPath: "/secrets/"
            readOnly: true
          - mountPath: /application/conf/local/
            name: credentials
            readOnly: true
          - mountPath: /dev/shm
            name: dshm
          resources:
            limits:
                cpu: "23"
                nvidia.com/gpu: 4
            requests:
                cpu: "23"
                nvidia.com/gpu: 4
        restartPolicy: OnFailure
        volumes:
        - name: secrets
          secret:
            secretName: secrets
        - name: credentials
          secret:
            secretName: credentials.yaml
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "200Gi"
        # nodeSelector:
        #   agentpool: jamcambf, jamcambf2, jamcambf3
        tolerations:
          - key: "group"
            operator: "Equal"
            value: "gpuBackFill"
            effect: "NoSchedule"
        imagePullSecrets:
            - name: regcred
        