#! /usr/bin/env python
"""Thenserflow 2 GPflow Models CLI"""
from curses import echo
import importlib
import typer
from gpflow2_models.parser import dataset, model

app = typer.Typer()
app.add_typer(dataset.app, name="dataset")
app.add_typer(model.app, name="model")
if __name__ == "__main__":
    app()
