"""
Module for cleanair parsers.
"""
from .complex import (
    DataBaseRoleParser,
    DatabaseSetupParser,
    FeatureNameParser,
    ModelFitParser,
    ModelValidationParser,
    SatelliteArgumentParser,
    ScootReadingArgumentParser,
    ScootForecastFeatureArgumentParser,
    FeatureSourceParser,
)
from .simple import (
    InsertMethodParser,
    WebParser,
    SecretFileParser,
    SourceParser,
    VerbosityParser,
    DurationParser,
    AQEReadingArgumentParser,
    LAQNReadingArgumentParser,
    ScootReadingFeatureArgumentParser,
    ScootRoadmapArgumentParser,
    SourceParser,
    StaticDatasetArgumentParser,
    StaticFeatureArgumentParser,
    StreetCanyonFeatureArgumentParser,
    UKMapFeatureArgumentParser,
)

__all__ = [
    "InsertMethodParser",
    "WebParser",
    "SecretFileParser",
    "SourceParser",
    "VerbosityParser",
    "DurationParser",
    "DataBaseRoleParser",
    "DatabaseSetupParser",
    "AQEReadingArgumentParser",
    "LAQNReadingArgumentParser",
    "ModelFitParser",
    "ModelValidationParser",
    "StaticFeatureArgumentParser",
    "SatelliteArgumentParser",
    "ScootForecastFeatureArgumentParser",
    "ScootReadingArgumentParser",
    "ScootReadingFeatureArgumentParser",
    "ScootRoadmapArgumentParser",
    "SourceParser",
    "FeatureSourceParser",
    "FeatureNameParser",
    "StaticDatasetArgumentParser",
    "StreetCanyonFeatureArgumentParser",
    "UKMapFeatureArgumentParser",
]
