name: Tests

on: [push]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
  test:
    runs-on: ubuntu-latest
    container:
      # run the tests on a pre-built container
      image: ${{ secrets.ACR_LOGIN_SERVER }}/cleanair_base:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dependencies
      run: |
        pip install --upgrade pip
        pip install -r containers/requirements.txt
    - name: Install
      run: pip install containers/cleanair
    - name: Test cleanair
      run: pytest containers/tests/test_cleanair/test_utils/test_dimension_calculator.py
    - name: Type hinting
      run: mypy --config-file .mypy.ini containers/cleanair